sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
# google cloud or AWS configuration
- gloud components update kubectl
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t arahanthjain/multi-k8s -f ./client/Dockerfile.dev ./client

script:
- docker run arahanthjain/multi-k8s npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master